### ISSUE TITLE
verify tables work

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#2]
I've seen that some of the tables haven't rendered properly. Can you propose steps to fix this?

<img width="725" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/16557730/c80f6655-a8cd-4d9c-9e0f-b20c5a2f0e60">

Seen on: http://127.0.0.1:5000/building-blocks/analyze-data/regressions-paneldata/random-effects

**Comment by thierrylahaije** [comment]
Hi @hannesdatta, 

This was already an issue that was stated in the readme, it is quite complex seen the current structures of tables in the .md:

> Tables currently to complex to parse to html by hardcoding. The most effective way would be to convert them all to html with ChatGPT (tried it, is very easy and quickly done) and add context to the styleguide on how people can add a html table (very easy and logical). Another option would to self design a new structure for a table. We should discuss this with Hannes.

We spoke about this and you said that you would like to keep the structure approximately the same without html, so the content needs to be checked so that the tables over the whole website are consistent. Currently, the markdown interpreter is unable to identify the tables and my custom interpreter cannot identify all of them either. I would suggest that we define a more clear structure for the table, which is easier to convert to tables e.g. :

```
{{ table }}
\| Column 1 | Column 2| Column 3 |\
| Cel 1| Cel 2 | Cel 3|
| Cel 1| Cel 2 | Cel 3|
{{ /table }}
```

This structure is easily readable when table rows are defined over multiple lines, since the interpreter can identify the columns by searching for the cells between the \ signs which define the table header. The interpreter can then count the columns in the header so that it knows how many cells to expect.

**Comment by thierrylahaije** [comment]
This issue is being tackled in issue #15, therefore this one is being closed.
