### ISSUE TITLE
recommendations: fix render issue

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website-flask#62]
![image](https://github.com/tilburgsciencehub/website-flask/assets/16557730/d73a3d7f-f2e2-4cc5-b826-4f366feb5a5a)

http://localhost:8070/topics/Computer-Setup/develop-coding-skills/coding-practices/principles-good-coding/#language-specific-style-guides

**Comment by thierrylahaije** [comment]
I found the problem. The markdown library did not recognize the list due to the space in front of the list:

<img width="669" alt="image" src="https://github.com/tilburgsciencehub/website-flask/assets/65568251/fed1eccb-1779-4b2c-8009-514592ba4393">

As soon as I removed this spacing in the .md, the error was fixed. This is something we need to clarify in the style guide.
